ElearningPlateforme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  
    path('accounts/', include('student.urls')),
    path('programmes/', include('programmes.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .views import (
    home_view, post_add, edit_post, delete_post
) 


urlpatterns = [
    # Accounts url
    path('', home_view, name='acceuil'),
    path('add_item/', post_add, name='add_item'),
    path('item/<int:pk>/edit/', edit_post, name='edit_post'),
    path('item/<int:pk>/delete/', delete_post, name='delete_post'),

]

programmes/urls.py
from django.urls import path
from programmes.views import *
app_name="programmes"
urlpatterns = [
    path('', NiveauListView.as_view(), name="niveaulist"),
    path('<slug:slug>', MatiereListView.as_view(), name="matierelist"),
    path('<str:niveau>/<slug:slug>/', LessonListView.as_view(), name="lessonlist"),
    path('<str:niveau>/<str:slug>/create/', LessonCreateView.as_view(), name="lessoncreate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/', LessonListViewDetail.as_view(), name="lessonlistdetail"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/update/',LessonUpdateView.as_view(), name="lessonupdate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/delete', LessonDeleteView.as_view(), name="lessondelete"),
    
]

programmes/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.conf import settings
# Create your models here.

User = settings.AUTH_USER_MODEL
class Niveaux(models.Model):
    nom = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField()


    def __str__(self):
        return self.nom


    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)  
        super().save(*args, **kwargs)  


class Matiere(models.Model):
    matiere_id = models.CharField(unique=True, max_length=40)
    nom = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    niveau = models.ForeignKey(Niveaux, on_delete=models.CASCADE, related_name='matiere')
    image = models.ImageField(upload_to='matiere', blank=True)
    description = models.TextField(max_length=500)


    def __str__(self):
        return self.nom


    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)  
        super().save(*args, **kwargs)  

class Lesson(models.Model):
    lesson_id = models.CharField(unique=True, max_length=40)
    niveau = models.ForeignKey(Niveaux, on_delete=models.CASCADE)
    creer_par = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE, related_name='lesson',null=True)
    nom = models.CharField(max_length=100,null=True) 
    slug = models.SlugField(blank=True, null=True)
    position = models.PositiveSmallIntegerField(verbose_name='chapitre no',null=True)  
    video = models.FileField(upload_to="Video", null=True, blank=True, verbose_name="cours en Video")
    fpe = models.FileField(upload_to="FPE", null=True, blank=True, verbose_name="fiche de presentation")
    pdf = models.FileField(upload_to="PDF", null=True, blank=True, verbose_name="Cours en pdf")

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.nom


    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)  
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("programmes:lessonlist", kwargs={"slug": self.matiere.slug, "niveau": self.niveau.slug})  

    

programmes/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import DetailView, ListView, DeleteView, UpdateView, CreateView, FormView
from .form import LessonForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect


class NiveauListView(ListView):
    context_object_name = 'niveaux'
    model = Niveaux
    template_name = 'programmes/niveaulist.html'

class MatiereListView(DetailView):
    context_object_name = 'niveau'
    model = Niveaux
    template_name = 'programmes/matierelist.html'

class LessonListView(DetailView):
    context_object_name = 'matieres'
    model = Matiere
    template_name = 'programmes/lessonlist.html'

class LessonListViewDetail(DetailView):
    context_object_name = 'lesson'
    model = Lesson
    template_name = 'programmes/lessonlistdetail.html'

class LessonCreateView(CreateView):
    form_class = LessonForm
    context_object_name = 'matieres'
    model = Matiere
    template_name = 'programmes/lessoncreate.html'

    def get_success_url(self):
        self.object = self.get_object()
        niveau = self.object.niveau
        return reverse_lazy('programmes:lessonlist', kwargs={'niveau':niveau, 'slug':self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        ls = form.save(commit=False)
        ls.creer_par = self.request.user
        ls.niveau = self.object.niveau
        ls.matiere = self.object
        ls.save()
        return HttpResponseRedirect(self.get_success_url())
    


class LessonUpdateView(UpdateView):
    fields = ('nom', 'position')
    context_object_name = 'lesson'
    model = Lesson
    template_name = 'programmes/lessonupdate.html'

class LessonDeleteView(DeleteView):
    model = Lesson
    context_object_name = "lesson"
    template_name = 'programmes/lessondelete.html'
    
    def get_success_url(self):
        niveau = self.object.niveau
        matiere = self.object.matiere
        return reverse_lazy("programmes:lessonlist", kwargs={'niveau':niveau, 'slug':matiere.slug})
      

templates/programmes/lessoncreate.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
       <div class="col-md-6">
   <form method="POST" enctype="multipart/form-data" class="bg-light p-4">
    <h4 class="my-4">Formulaire de création d'une leçon</h4>
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit" value="Confirmer la création" class="btn btn-primary mt-3">
   </form>
</div>
</div>
</div>

{% endblock %}

templates/programmes/lessondelete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Êtes-vous sûr(e) de vouloir supprimer cette leçon?</h1>
    <div class="d-flex justify-content-center">
        <form method="POST">
            {% csrf_token %}
            <div class="d-flex justify-content-center">
                <input class="btn btn-danger mr-3" type="submit" value="Supprimer définitivement">
                <a class="btn btn-primary" href="{% url 'programmes:lessonlistdetail' slug=lesson.slug matiere=lesson.matiere.slug niveau=lesson.niveau.slug %}">Annuler</a>
                
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/programmes/lessonlist.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6">
                <h2>{{ matieres.niveau.nom }} >>> {{ matieres.nom }}</h2>
            </div>
            <div class="col-md-6">
                <div class="input-group mb-3">
                    {% if request.user.is_superuser or request.user.is_lecturer %}
                    <button class="btn btn-success" type="button" id="button-add-lesson">
                        Ajouter Une leçon
                    </button>
                    {% endif %}
                    <div class="input-group-append" style="margin-left: 10px;">
                        <input type="text" class="form-control" placeholder="Rechercher par nom" aria-label="Rechercher une leçon" id="search-input">
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            {% for lesson in matieres.lesson.all  %}
                <div class="col-md-6">
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">Chapitre-{{ lesson.position }} {{ lesson.nom }}</h5>
                            <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug matiere=matieres.slug niveau=matieres.niveau.slug %}" class="btn btn-primary">Voir les détails</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('#button-add-lesson').click(function() {
                window.location.href = '{% url 'programmes:lessoncreate' niveau=matieres.niveau.slug slug=matieres.slug %}';
            });

            $('#search-input').on('input', function() {
                var searchText = $(this).val().toLowerCase();
                $('.card-title').each(function() {
                    var currentText = $(this).text().toLowerCase();
                    if (currentText.indexOf(searchText) != -1) {
                        $(this).parents('.card').show();
                    } else {
                        $(this).parents('.card').hide();
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/programmes/lessonlistdetail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
       
        <h3 class="mb-4">La leçon intitulée {{ lesson.nom }} a été créée par Prof: {{ lesson.creer_par }}</h3>
        {% if request.user.is_superuser %}
        <a href="{% url 'programmes:lessonupdate' niveau=lesson.niveau.slug matiere=lesson.matiere.slug slug=lesson.slug %}" class="btn btn-primary mr-2">Modifier la leçon</a>
        <a href="{% url 'programmes:lessondelete' niveau=lesson.niveau.slug matiere=lesson.matiere.slug slug=lesson.slug %}" class="btn btn-danger">Supprimer la leçon</a> <br><br>
        {% endif %}
        {% if lesson.video %}
        <div style="width: 90%; margin: auto;">
            <video width="100%" controls>
              <source src="{{ lesson.video.url }}" type="video/mp4">
              Your browser does not support HTML video.
            </video>
          </div>
          <p style="font-size: 24px; color: #333; font-weight: bold; text-align: center;">Titre du cours: {{ lesson.nom }}</p>

          
           
        {% endif %}
        <div class="row">
            {% if lesson.pdf %}
                <div class="col-md-6 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Informations supplementaires en PDF</h5>
                            <a href="{{ lesson.pdf }}" class="btn btn-primary">Télécharger le PDF</a>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if lesson.fpe %}
                <div class="col-md-6 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">La leçon en PPT</h5>
                            <a href="{{ lesson.fpe }}" class="btn btn-primary">Télécharger le PPT</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        
    </div>
{% endblock %}

templates/programmes/lessonupdate.html
{% extends 'base.html' %}

{% block content %}
  <div class="container py-4">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">{{ form.title }}</div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Confirmer la modification" class="btn btn-primary">
              <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug matiere=lesson.matiere.slug niveau=lesson.niveau.slug %}" class="btn btn-secondary">Annuler</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/programmes/matierelist.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
    
    <div class="row">
      <div class="col-md-6">
        <h4 class="my-4">Listes des cours du niveau : {{ niveau.nom }}</h4>
      </div>
      <div class="col-md-12 justify-content-end d-flex">
        <a class="btn btn-primary" href="{% url 'programmes:niveaulist' %}">Retour</a>
      </div>
    </div>
    <div class="my-4"></div>
    <div class="row">
      {% for matiere in niveau.matiere.all %}
      <div class="col-lg-4 mb-4">

        <div class="card">
          <img src="{{ matiere.image.url }}" class="card-img-top" alt="{{ matiere.nom }} Image"
            style="height: 200px; width: 100%; object-fit: cover;">
          <div class="card-body">
            <h5 class="card-title">{{ matiere.nom }}</h5>
            <p class="card-text">{{ matiere.description }}</p>
            <a href="{% url 'programmes:lessonlist' slug=matiere.slug niveau=niveau.slug %}"
              class="btn btn-primary">Voir les leçons</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  
  {% endblock %}

templates/programmes/niveaulist.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4 class="mb-4 d-inline">Liste des niveaux</h4>
    </div>
    <div class="col-md-6 d-flex justify-content-end">
      <a class="btn btn-primary" href="{% url 'acceuil' %}">Acceuil</a>
    </div>
  </div>
  <div class="my-4"></div>
  <div class="list-group">
    {% for niveau in niveaux %}
    <a href="{% url 'programmes:matierelist' slug=niveau.slug %}" class="list-group-item list-group-item-action">{{ niveau.nom }}</a>
    {% endfor %}
  </div>
</div>

{% endblock %}