ElearningPlateforme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  
    path('accounts/', include('student.urls')),
    path('programmes/', include('programmes.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .views import (
    home_view, post_add, edit_post, delete_post
) 


urlpatterns = [
    # Accounts url
    path('', home_view, name='acceuil'),
    path('add_item/', post_add, name='add_item'),
    path('item/<int:pk>/edit/', edit_post, name='edit_post'),
    path('item/<int:pk>/delete/', delete_post, name='delete_post'),

]

programmes/urls.py
from django.urls import path
from programmes.views import *
app_name="programmes"
urlpatterns = [
    path('', NiveauListView.as_view(), name="niveaulist"),
    path('<slug:slug>', MatiereListView.as_view(), name="matierelist"),
    path('<str:niveau>/<slug:slug>/', LessonListView.as_view(), name="lessonlist"),
    path('<str:niveau>/<str:slug>/create/', LessonCreateView.as_view(), name="lessoncreate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/', LessonListViewDetail.as_view(), name="lessonlistdetail"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/update/',LessonUpdateView.as_view(), name="lessonupdate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/delete', LessonDeleteView.as_view(), name="lessondelete"),
    
]

student/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.conf import settings

from django.db.models import Q
from PIL import Image

from .validators import ASCIIUsernameValidator

User = settings.AUTH_USER_MODEL

# LEVEL_COURSE = "Level course"
LP = "Licence"
MS = "Master"

LEVEL = (
    # (LEVEL_COURSE, "Level course"),
    (LP, "Licence"),
    (MS, "Master"),
)


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_lecturer = models.BooleanField(default=False)
    is_dep_head = models.BooleanField(default=False)
    phone = models.CharField(max_length=60, blank=True, null=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    picture = models.ImageField(upload_to='profile_pictures/%y/%m/%d/', default='default.png', null=True)
    email = models.EmailField(blank=True, null=True)

    username_validator = ASCIIUsernameValidator()

    # objects = UserManager()

    @property
    def get_full_name(self):
        full_name = self.username
        if self.first_name and self.last_name:
            full_name = self.first_name + " " + self.last_name
        return full_name

    def __str__(self):
        return '{} ({})'.format(self.username, self.get_full_name)

    @property
    def get_user_role(self):
        if self.is_superuser:
            return "Admin"
        elif self.is_student:
            return "Student"
        elif self.is_lecturer:
            return "Prof"
    def get_picture(self):
        try:
            return self.picture.url
        except:
            no_picture = settings.MEDIA_URL + 'default.png'
            return no_picture

    def get_absolute_url(self):
        return reverse('profile_single', kwargs={'id': self.id})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            img = Image.open(self.picture.path)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.picture.path)
        except:
            pass

    def delete(self, *args, **kwargs):
        if self.picture.url != settings.MEDIA_URL + 'default.png':
            self.picture.delete()
        super().delete(*args, **kwargs)


class StudentManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(level__icontains=query) | 
                         Q(department__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() 
        return qs


class Student(models.Model):
    student = models.OneToOneField(User, on_delete=models.CASCADE)
    level = models.CharField(max_length=25, choices=LEVEL, null=True)

    objects = StudentManager()

    def __str__(self):
        return self.student.get_full_name

    def get_absolute_url(self):
        return reverse('profile_single', kwargs={'id': self.id})

    def delete(self, *args, **kwargs):
        self.student.delete()
        super().delete(*args, **kwargs)

templates/admin_panel.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 p-5 bg-light">
            <h2 class="text-center"><i class="fas fa-user-tie"></i> Admin Panel</h2>
            <br>
            <br>
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger">
                            <i class="fas fa-exclamation-circle"></i> {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-success">
                            <i class="fas fa-check-circle"></i> {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <div class="admin-panel">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Manage</h4>
                        <a class="btn btn-sm btn-secondary" href="{% url 'prof_list' %}">Manage Profs &raquo;</a>
                        <p><span>&#x2192;</span> (Create, Update & Delete) prof</p>
                        <hr>
                        <a class="btn btn-sm btn-secondary" href="{% url 'student_list' %}">Manage Students &raquo;</a>
                        <p><span>&#x2192;</span> (Create, Update & Delete) students</p>
                        <hr>
                        <a class="btn btn-sm btn-secondary" href="{% url 'programmes:niveaulist' %}">Manage Courses &raquo;</a>
                        <p><span>&#x2192;</span> (Create, Update & Delete) courses</p>
                        <hr>
                        <a class="btn btn-sm btn-secondary" href="{% url 'acceuil' %}">Create News & Events &raquo;</a>
                        <p><span>&#x2192;</span> (Create, Update & Delete) News & Events</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Elearning</title>
   <link rel="icon" type="image/png" href="{% static 'images/icon/favicon-16x16.png' %}">
   <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
   <link rel="stylesheet" href="{% static 'styles/style.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
   <link rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
   <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"
      integrity="sha512-z4OUqw38qNLpn1libAN9BsoDx6nbNFio5lA6CuTp9NlK83b89hgyCVq+N5FdBJptINztxn1Z3SaKSKUS5UP60Q=="
      crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
      integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
      crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
   <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
   <link href="../static/css/styleIndex.css" rel="stylesheet">

   {{ form.media }}
</head>

<body>
   <!-- Navbar Starts -->
   <nav class="navbar sticky-top navbar-expand-lg navbar-dark navbar-mod">
      <div class="container-fluid">
         <a class="navbar-brand fw-bold fs-5 px-2 py-1" target="_blank" data-bs-toggle="tooltip"
            data-bs-placement="bottom" title="Access admin panel">Elearning</a>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
            <span class=" navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               <li class="nav-item">
                  <a class="nav-link active fw-bold" aria-current="page" href="{% url 'acceuil' %}"
                     data-bs-toggle="tooltip" data-bs-placement="bottom" title="Course home page"><i
                        class="fas fa-home"></i> Acceuil</a>
               </li>

               {% if request.user.is_superuser %}
               <li class="nav-item">
                  <a class="nav-link active fw-bold" aria-current="page" href="{% url 'student_list' %}"
                     data-bs-toggle="tooltip" data-bs-placement="bottom" title="Course home page"><i
                        class="fas fa-user-graduate"></i> Students</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link active fw-bold" aria-current="page" href="{% url 'prof_list' %}"
                     data-bs-toggle="tooltip" data-bs-placement="bottom" title="Course home page"><i
                        class="fas fa-user-graduate"></i> Prof</a>
               </li>
               {% endif %}
               {% if user.is_authenticated %}

               <li class="nav-item">
                  <a class="nav-link active fw-bold" data-bs-toggle="tooltip" data-bs-placement="bottom"
                     href="{% url 'programmes:niveaulist' %}" title="Cours"><i class="fas fa-book"></i> Cours</a>
               </li>
            </ul>

            <div class="dropdown">
               <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  <img class="profile-pic" src="{{ request.user.picture.url }}">
                  {{ request.user.get_full_name|truncatechars:15 }}
               </button>
               <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  {% if request.user.is_superuser %}
                  <a class="dropdown-item" href="{% url 'admin_panel' %}"><i class="fas fa-user-tie"></i>Admin Panel</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'profile' %}"><i class="fas fa-address-card"></i>Profile</a>
                  <a class="dropdown-item" href="{% url 'edit_profile' %}"><i class="fas fa-cogs"></i>Parameter</a>
                  <hr>
                  <div class="dropdown-divider"></div>
                  <div style="display: flex; justify-content: center; align-items: center;">
                     <a class="btn btn-danger" href="{% url 'logout' %}">
                        <i class="fas fa-sign-out-alt"></i> logout
                     </a>
                  </div>
               </div>

            </div>

            {% endif %}

         </div>
      </div>
   </nav>

   <div class="container mt-4">
      <div class="row justify-content-left">
         <div class="col-md-8">
            <div class="text-left">
               <h3 class="mb-4">Welcome {{request.user.username}}</h3>
            </div>
         </div>
      </div>
   </div>

   <!-- Navbar Ends -->
   {% block content %}
   {% endblock %}
   <script src=" {% static 'js/bootstrap.bundle.min.js' %} "></script>
   <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
   
   <script>
      $(document).ready(function () {
         $('.au-input').focus(function () {
            $('#top-navbar').attr('class', 'dim');
            $('#side-nav').css('pointer-events', 'none');
            $('#main-content').css('pointer-events', 'none');
         });
         $('.au-input').focusout(function () {
            $('#top-navbar').removeAttr('class');
            $('#side-nav').css('pointer-events', 'auto');
            $('#main-content').css('pointer-events', 'auto');
         });
      })
   </script>

   {% block js %}
   {% endblock js %}

   <footer id="footer">
      <div class="container d-md-flex-center py-4">
         <div class="me-md-auto text-center text-md-start">
            <div class="copyright">
               &copy; Copyright <strong><span>Emsi</span></strong>. All Rights Reserved
            </div>
            <div class="credits">

               made by Anas Jegoual , Badr Ait Hammou and Zineb Naciri</a>
            </div>
         </div>

      </div>
   </footer>
</body>

</html>